### PR TITLE
Master3

### PR DESCRIPTION
**Pull request by BCCghspace**
Hi Anna, I am currently in class right now. You can start either writing or experimenting with the regression variables.

### CODE REVIEW

**Review by annaduan09 — APPROVED** [review]

**Comment by annaduan09** [comment]
Hi Bingchu,

Sounds good, thanks.
Anna

**Comment by annaduan09** [comment]
Btw - were you able to figure out the spatial lag plots?

**Comment by BCCghspace** [comment]
Hi Anna,

I am not sure which one are you referring to? I just scrolled through and I think we have all the figures now. This idea of annotating the neighborhood occurred to me when I was in class and I think it would be really interesting to look into those neighborhoods. Overall we are over predicting the price, but some have more variance than the others.

BTW, which part are you working on right now? I can take the other task.

Best,
Bingchu

**Comment by annaduan09** [comment]
Hi Bingchu,

Figure 13 is cool - yes, we should label neighborhoods.

We're still missing two of the figures from section 10 and I'm not sure how to get them to work. I'm also unclear on how to map residual. Could you take a look? I also feel like neighborhood mape doesn't look right (too low)

I'm writing right now and finalizing some figures like corr plot. 

Best,
Anna

**Comment by BCCghspace** [comment]
Sure! I will look at them now.

Best,
Bingchu

**Comment by annaduan09** [comment]
Great! Btw can you pull, I just made a commit.

**Comment by BCCghspace** [comment]
Hi Anna,

I just fixed the fig10. Try now and see if that works:) I am afraid I would have to sleep now. Let’s meet tonight at 11.

Best,
Bingchu

**Comment by annaduan09** [comment]
Hi Bingchu,

Great- thank you!! Of course, sleep!

See you later,
Anna

**Pull request merged**
